############## Spring App properties ###############
spring:
  application:
    name: '@project.artifactId@'
  config:
    import:
    - "optional:configserver:"
  cloud:
    config:
      uri:
      - http://localhost:8888
  datasource:
    url: jdbc:h2:file:./target/data/products-db
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
############## Info properties ###############
info:
  app:
    name: '@project.artifactId@'
    version: '@project.version@'
############## Log properties ###############
#logging:
#  level:
#    '[com.craftsman.restservice]': DEBUG
############## Server properties ###############
server:
  port: 8080
  tomcat:
    connection-timeout: 5s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  servlet:
    contextPath: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true  
############## Springdoc properties ###############    
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
    version: 'OPENAPI_3_0'  
  swagger-ui:
    path: /openapi/swagger-ui.html